- hosts: "{{ hosts }}"
  roles:
    - role: mysql57
  vars:
    mysql_root_password: Super_P@s$0rd
    mysql_databases:
      - name: example2_db
        encoding: latin1
        collation: latin1_general_ci
    mysql_users:
      - name: example2_user
        host: "%"
        password: Sime32_U$er_p@ssw0rd
        priv: "example2_db.*:ALL"
    mysql_port: 3306
    mysql_bind_address: '0.0.0.0'
    mysql_daemon: mysqld
    mysql_version: 5.7
