- name: Remove anonymous MySQL users
  mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    config_file: "/etc/my.cnf"
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  ignore_errors: yes
- name: Remove MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    config_file: "/etc/my.cnf"
  vars:
    ansible_python_interpreter: /usr/bin/python2.6
  ignore_errors: yes

# - name: Create mysql Clinet user
#   mysql_user:
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#     name: "{{ item.name }}"
#     password: "{{ item.password }}"
#     priv: '*.*:ALL,GRANT'
#     state: present
#     host: '%'
#   with_items:
#     - "{{ mysql_users }}"
