# ref : https://www.soudegesu.com/en/mysql/mysql8-password/
- name: Install requirements
  yum:
    name: "{{ mysql_default_python_packages }}"
    state: present
    update_cache: true
  register: result
  until: result is succeeded

- name: Create group MySQL
  group:
    name: mysql
    state: present

- name: ADD MySQL user
  user:
    name: mysql
    shell: /bin/false
    group: mysql
    append: yes

- name: Create MySQL Engine directory
  file:
    path: "{{ mysql_default_base_dir }}"
    state: directory
    owner: mysql
    group: mysql

- name: Create MySQL directory data and log
  file:
    path: "{{ mysql_default_root_data_dir }}/{{ item }}"
    owner: mysql
    group: mysql
    mode: 0755
    recurse: yes
    state: directory
  with_items:
    - "mysqldata"
    - "mysqltmp"
    - "mysqllog/error"
    - "mysqllog/binary"
    - "mysqllog/slow"
    - "mysqllog/redo"
    - "mysqllog/undo"

- name: List {{ mysql_default_root_data_dir }}
  shell: "ls -lht {{ mysql_default_root_data_dir }}"
  register: result
- name: show {{ mysql_default_root_data_dir }}
  debug:
    msg: "{{ result.stdout_lines }}"

- name: Create MySQL error log file
  file:
    path: "{{ mysql_default_error_log_file }}"
    owner: mysql
    group: mysql
    state: touch
