- name: Create group MySQL
  group:
    name: mysql
    state: present
  become: yes

- name: ADD MySQL user
  user:
    name: mysql
    shell: /bin/false
    group: mysql
    append: yes
  become: yes

- name: Download and Extract MySQL Generic binary version
  unarchive:
    src: "{{ download_url }}"
    dest: "/tmp"
    remote_src: yes
