- name: Create group MySQL
  group:
    name: mysql
    state: present
    
- name: ADD MySQL user
  user:
    name: mysql
    shell: /bin/false
    group: mysql
    append: yes

- name: Create MySQL Engine directory
  file:
    path: /mysql
    state: directory
    owner: mysql
    group: mysql

- name: Download and Extract MySQL Generic binary version
  unarchive:
    src: "{{ download_url }}"
    dest: "/mysql"
    remote_src: yes
