- name: Create group MySQL
  group:
    name: mysql
    state: present

- name: ADD MySQL user
  user:
    name: mysql
    shell: /bin/false
    group: mysql
    append: yes

- name: Create MySQL Engine directory
  file:
    path: /mysql
    state: directory
    owner: mysql
    group: mysql

- name: Create MySQL directory data and log
  file:
    path: "/data/{{ item }}"
    owner: mysql
    group: mysql
    mode: 0755
    recurse: yes
    state: directory
  with_items:
    - "mysqldata"
    - "mysqllog/error"
    - "mysqllog/binary"
    - "mysqllog/slow"
    - "mysqllog/redo"
    - "mysqllog/undo"

  - name: List /data
    shell: "ls -lht /data"
    register: result
  - name: show /data
    debug:
      msg: "{{ result.stdout }}"

- name: Download and Extract MySQL Generic binary version
  unarchive:
    src: "{{ download_url }}"
    dest: "/mysql"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: Install MySQL
  async: 10
  poll: 0
  shell:
    "./bin/mysqld"
  args:
    -
    chdir: "/mysql/bin"
  register: result
